#!/usr/bin/env node
/*
 * stress.cjs -- an adversarial structural/consistency sweep, distinct in PURPOSE from verify.cjs.
 *
 * verify.cjs proves the MATH (every computed number independently re-derived from the page's own
 * pure functions). stress.cjs checks everything else a reconciliation test doesn't catch: no
 * employer-name leak, every "real"-badged claim is actually explained nearby (not a bare
 * assertion), illustrative content is never silently promoted to real, structural tag/tab-count
 * balance, and that every alert/verdict function this build's 5 phases added has BOTH its
 * branches actually exercised somewhere in verify.cjs -- a coverage-of-coverage check.
 *
 * This is a genuine second layer, not a renamed copy of verify.cjs -- and it is explicitly NOT an
 * attempt to match the reference project-controls-command-center's own stress.cjs at its literal
 * scale (2,974 assertions accumulated over a much larger build). Scoped honestly to what this
 * build's actual surface area warrants; grows as the build does, same as verify.cjs has.
 */
"use strict";
const fs = require("fs");
const path = require("path");

let failures = 0;
function check(condition, label, detail) {
  if (condition) { console.log("pass:", label); }
  else { failures++; console.error("FAIL:", label, detail !== undefined ? "-- " + detail : ""); }
}

const indexHtml = fs.readFileSync(path.join(__dirname, "index.html"), "utf8");
const readme = fs.readFileSync(path.join(__dirname, "README.md"), "utf8");
const verifyJs = fs.readFileSync(path.join(__dirname, "verify.cjs"), "utf8");

console.log("--- No employer-name leak in the public methodology demo (index.html only) ---");
// ada-fit.html and README are EXPECTED to name Ada Infrastructure -- that's their whole purpose.
// index.html is the general-purpose public demo and carries the no-name-leak rule.
[
  { pattern: "Ada Infrastructure", re: /Ada Infrastructure/ },
  { pattern: "B.E. Meyers", re: /B\.E\. Meyers/ },
  { pattern: "BEM (word-boundary)", re: /\bBEM\b/ },
].forEach(({ pattern, re }) => {
  check(!re.test(indexHtml), `index.html has no leak of "${pattern}"`);
});

console.log("--- Structural tag balance ---");
function countTag(html, tag) {
  const open = (html.match(new RegExp(`<${tag}\\b`, "g")) || []).length;
  const close = (html.match(new RegExp(`</${tag}>`, "g")) || []).length;
  return { open, close };
}
["div", "section"].forEach((tag) => {
  const c = countTag(indexHtml, tag);
  check(c.open === c.close, `index.html <${tag}> tags balanced (${c.open} open / ${c.close} close)`, `${c.open} vs ${c.close}`);
});

console.log("--- Tab count matches panel count (a real bug class if they diverge) ---");
const tabCount = (indexHtml.match(/role="tab"/g) || []).length;
const panelCount = (indexHtml.match(/class="tabpanel/g) || []).length;
check(tabCount === panelCount, `tab buttons (${tabCount}) match tabpanels (${panelCount})`, `${tabCount} vs ${panelCount}`);

console.log("--- Every 'real' badge is explained somewhere in its own <section>, not a bare assertion ---");
// Section-scoped, not a fixed character window: a heading-level badge's citation legitimately
// lives several hundred chars later, past a lede/card/KPI block, inside the same <section>...
// </section> -- checking a fixed window flagged real, cited content as "unexplained" simply
// because the citation sat past an arbitrary cutoff (a bug in the check, not the page, caught by
// actually inspecting the failing text before dismissing it -- see PHASE5 findings in commit log).
const EXPLANATION_TOKENS = /AACE|RICS|ICMS|Uptime Institute|Turner|Archdesk|irecruit|ANSI\/EIA|\$208K|100\+ bid|master-data|drawdown ratio|risk exposure|priced risk|coverage ratio|Contingency & Risk tab|cited public source|re-checking|already computed|generated by|read live|reads live|DuckDB|independently re-derives|runs locally/i;
const sections = indexHtml.match(/<section\b[\s\S]*?<\/section>/g) || [];
check(sections.length > 0, "at least one <section> found to scope the check against (regex didn't silently match zero)");
let realBadgeChecks = 0;
sections.forEach((sec, si) => {
  const badgeCount = (sec.match(/badge real/g) || []).length;
  if (badgeCount === 0) return;
  const flat = sec.replace(/\s+/g, " ");
  check(EXPLANATION_TOKENS.test(flat), `section #${si + 1} carrying a 'real' badge is explained somewhere in that same section, not a bare claim`, flat.slice(0, 90));
  realBadgeChecks++;
});
check(realBadgeChecks > 0, "at least one section-scoped 'real' badge check actually ran");

console.log("--- Illustrative sections never carry a bare 'real' badge on their own heading ---");
check(!/Priced Risk Register[^\n]*badge real/.test(indexHtml), "risk register heading doesn't carry a bare 'real' badge (methodology is real, rows aren't)");
check(!/Consultant Deliverable Scorecard[^\n]*badge real/.test(indexHtml), "consultant scorecard heading doesn't carry a bare 'real' badge");
check(!/Commercial Action Item Register[^\n]*badge real/.test(indexHtml), "actions register heading doesn't carry a bare 'real' badge");

console.log("--- Coverage-of-coverage: every Phase 1-5 verdict function has BOTH branches tested in verify.cjs ---");
const BRANCH_PAIRS = [
  ["produce the WARN branch", "produce the OK branch"],
  ["BLOCKED with this build's real numbers", "CLEARED branch"],
  ["non-elevated branch", "correctly trips ELEVATED"],
  ["DISPUTE branch", "recommend SETTLE"],
  ["a mode below min clamps", "a mode above max clamps"],
];
BRANCH_PAIRS.forEach(([a, b], i) => {
  const hasA = verifyJs.includes(a);
  const hasB = verifyJs.includes(b);
  check(hasA && hasB, `verdict pair #${i + 1} ("${a}" / "${b}") both appear in verify.cjs`, `${hasA}/${hasB}`);
});

console.log("--- README's stated tab count stays traceable to the real live markup ---");
const readmeTabCountMatch = readme.match(/(\d+) tabs/);
if (readmeTabCountMatch) {
  const readmeTabs = parseInt(readmeTabCountMatch[1], 10);
  check(readmeTabs === tabCount, `README's stated tab count (${readmeTabs}) matches the real live tab count (${tabCount})`, `${readmeTabs} vs ${tabCount}`);
} else {
  failures++;
  console.error("FAIL: README doesn't state a tab count in the expected 'N tabs' form -- can't check it");
}

console.log("");
if (failures > 0) {
  console.error(failures + " stress check(s) FAILED");
  process.exit(1);
} else {
  console.log("All stress checks passed.");
  process.exit(0);
}
