#!/usr/bin/env node
/*
 * stress.cjs -- an adversarial structural/consistency sweep, distinct in PURPOSE from verify.cjs.
 *
 * verify.cjs proves the MATH (every computed number independently re-derived from the page's own
 * pure functions). stress.cjs checks everything else a reconciliation test doesn't catch: no
 * employer-name leak, every "real"-badged claim is actually explained nearby (not a bare
 * assertion), illustrative content is never silently promoted to real, structural tag/tab-count
 * balance, and that every alert/verdict function this build's 5 phases added has BOTH its
 * branches actually exercised somewhere in verify.cjs -- a coverage-of-coverage check.
 *
 * This is a genuine second layer, not a renamed copy of verify.cjs -- and it is explicitly NOT an
 * attempt to match the reference project-controls-command-center's own stress.cjs at its literal
 * scale (2,974 assertions accumulated over a much larger build). Scoped honestly to what this
 * build's actual surface area warrants; grows as the build does, same as verify.cjs has.
 */
"use strict";
const fs = require("fs");
const path = require("path");

let failures = 0;
function check(condition, label, detail) {
  if (condition) { console.log("pass:", label); }
  else { failures++; console.error("FAIL:", label, detail !== undefined ? "-- " + detail : ""); }
}

const indexHtml = fs.readFileSync(path.join(__dirname, "index.html"), "utf8");
const readme = fs.readFileSync(path.join(__dirname, "README.md"), "utf8");
const verifyJs = fs.readFileSync(path.join(__dirname, "verify.cjs"), "utf8");

console.log("--- No employer-name leak in the public methodology demo (index.html only) ---");
// ada-fit.html and README are EXPECTED to name Ada Infrastructure -- that's their whole purpose.
// index.html is the general-purpose public demo and carries the no-name-leak rule.
[
  { pattern: "Ada Infrastructure", re: /Ada Infrastructure/ },
  { pattern: "B.E. Meyers", re: /B\.E\. Meyers/ },
  { pattern: "BEM (word-boundary)", re: /\bBEM\b/ },
].forEach(({ pattern, re }) => {
  check(!re.test(indexHtml), `index.html has no leak of "${pattern}"`);
});

console.log("--- Structural tag balance ---");
function countTag(html, tag) {
  const open = (html.match(new RegExp(`<${tag}\\b`, "g")) || []).length;
  const close = (html.match(new RegExp(`</${tag}>`, "g")) || []).length;
  return { open, close };
}
["div", "section"].forEach((tag) => {
  const c = countTag(indexHtml, tag);
  check(c.open === c.close, `index.html <${tag}> tags balanced (${c.open} open / ${c.close} close)`, `${c.open} vs ${c.close}`);
});

console.log("--- Tab count matches panel count (a real bug class if they diverge) ---");
const tabCount = (indexHtml.match(/role="tab"/g) || []).length;
const panelCount = (indexHtml.match(/class="tabpanel/g) || []).length;
check(tabCount === panelCount, `tab buttons (${tabCount}) match tabpanels (${panelCount})`, `${tabCount} vs ${panelCount}`);

console.log("--- Every 'real' badge is explained somewhere in its own <section>, not a bare assertion ---");
// Section-scoped, not a fixed character window: a heading-level badge's citation legitimately
// lives several hundred chars later, past a lede/card/KPI block, inside the same <section>...
// </section> -- checking a fixed window flagged real, cited content as "unexplained" simply
// because the citation sat past an arbitrary cutoff (a bug in the check, not the page, caught by
// actually inspecting the failing text before dismissing it -- see PHASE5 findings in commit log).
const EXPLANATION_TOKENS = /AACE|RICS|ICMS|Uptime Institute|Turner|Archdesk|irecruit|ANSI\/EIA|\$208K|100\+ bid|master-data|drawdown ratio|risk exposure|priced risk|coverage ratio|Contingency & Risk tab|cited public source|re-checking|already computed|generated by|read live|reads live|DuckDB|independently re-derives|runs locally|Wood Mackenzie|RMI|Eckert Seamans|Data Center Knowledge|EnkiAI|Cummins/i;
const sections = indexHtml.match(/<section\b[\s\S]*?<\/section>/g) || [];
check(sections.length > 0, "at least one <section> found to scope the check against (regex didn't silently match zero)");
let realBadgeChecks = 0;
sections.forEach((sec, si) => {
  const badgeCount = (sec.match(/badge real/g) || []).length;
  if (badgeCount === 0) return;
  const flat = sec.replace(/\s+/g, " ");
  check(EXPLANATION_TOKENS.test(flat), `section #${si + 1} carrying a 'real' badge is explained somewhere in that same section, not a bare claim`, flat.slice(0, 90));
  realBadgeChecks++;
});
check(realBadgeChecks > 0, "at least one section-scoped 'real' badge check actually ran");

console.log("--- Illustrative sections never carry a bare 'real' badge on their own heading ---");
check(!/Priced Risk Register[^\n]*badge real/.test(indexHtml), "risk register heading doesn't carry a bare 'real' badge (methodology is real, rows aren't)");
check(!/Consultant Deliverable Scorecard[^\n]*badge real/.test(indexHtml), "consultant scorecard heading doesn't carry a bare 'real' badge");
check(!/Commercial Action Item Register[^\n]*badge real/.test(indexHtml), "actions register heading doesn't carry a bare 'real' badge");

console.log("--- Coverage-of-coverage: every Phase 1-5 verdict function has BOTH branches tested in verify.cjs ---");
const BRANCH_PAIRS = [
  ["produce the WARN branch", "produce the OK branch"],
  ["BLOCKED with this build's real numbers", "CLEARED branch"],
  ["non-elevated branch", "correctly trips ELEVATED"],
  ["DISPUTE branch", "recommend SETTLE"],
  ["a mode below min clamps", "a mode above max clamps"],
];
BRANCH_PAIRS.forEach(([a, b], i) => {
  const hasA = verifyJs.includes(a);
  const hasB = verifyJs.includes(b);
  check(hasA && hasB, `verdict pair #${i + 1} ("${a}" / "${b}") both appear in verify.cjs`, `${hasA}/${hasB}`);
});

console.log("--- README's stated tab count stays traceable to the real live markup ---");
const readmeTabCountMatch = readme.match(/(\d+) tabs/);
if (readmeTabCountMatch) {
  const readmeTabs = parseInt(readmeTabCountMatch[1], 10);
  check(readmeTabs === tabCount, `README's stated tab count (${readmeTabs}) matches the real live tab count (${tabCount})`, `${readmeTabs} vs ${tabCount}`);
} else {
  failures++;
  console.error("FAIL: README doesn't state a tab count in the expected 'N tabs' form -- can't check it");
}

console.log("--- Okabe-Ito status-color tokens: all 4 duplicated theme blocks stay in sync ---");
// index.html declares dark-mode tokens in 2 places (:root and :root[data-theme="dark"]) and
// light-mode tokens in 2 places (@media prefers-color-scheme + :root[data-theme="light"]) -- a
// real risk this build has hit before (drift between duplicated blocks). Confirms all 4 actually
// carry the real Okabe-Ito-derived, WCAG-AA-contrast-checked values, not a stale/half-updated copy.
const darkTokenBlocks = (indexHtml.match(/--c-success:9 170 124; --c-warning:218 146 11; --c-danger:242 93 13;/g) || []).length;
const lightTokenBlocks = (indexHtml.match(/--c-success:6 121 89; --c-warning:131 87 7; --c-danger:170 65 9;/g) || []).length;
check(darkTokenBlocks === 2, "both dark-mode color-token blocks carry the same Okabe-Ito-derived values", `found ${darkTokenBlocks}, expected 2`);
check(lightTokenBlocks === 2, "both light-mode color-token blocks carry the same Okabe-Ito-derived values", `found ${lightTokenBlocks}, expected 2`);

console.log("--- All 20-KPI formula/methodology explainer divs have matching content, in both directions ---");
const explainerDivIds = [...indexHtml.matchAll(/class="explainer" id="(exp\w+)"/g)].map((m) => m[1]);
const explainerObjMatch = indexHtml.match(/var kpiExplainers = \{([\s\S]*?)\n  \};/);
check(explainerDivIds.length === 30, `found all 30 expected explainer divs in the HTML`, `found ${explainerDivIds.length}`);
if (explainerObjMatch) {
  const explainerKeys = [...explainerObjMatch[1].matchAll(/^\s*(exp\w+):/gm)].map((m) => m[1]);
  const divsWithNoContent = explainerDivIds.filter((id) => !explainerKeys.includes(id));
  const keysWithNoDiv = explainerKeys.filter((id) => !explainerDivIds.includes(id));
  check(divsWithNoContent.length === 0, "every explainer div id has matching content in kpiExplainers (no silently-empty tooltip)", JSON.stringify(divsWithNoContent));
  check(keysWithNoDiv.length === 0, "every kpiExplainers key has a matching div in the HTML (no orphaned content nobody can see)", JSON.stringify(keysWithNoDiv));
} else {
  failures++; console.error("FAIL: could not find the kpiExplainers object in index.html to check against");
}

console.log("--- TAB_INFO (hover-preview drawer content) covers exactly the real 11 tabs ---");
const tabInfoMatch = indexHtml.match(/var TAB_INFO = \{([\s\S]*?)\n  \};/);
if (tabInfoMatch) {
  const tabInfoKeys = [...tabInfoMatch[1].matchAll(/^\s*(\w+):\s*\{/gm)].map((m) => m[1]);
  const realTabs = ["overview","exec","cost","contingency","governance","portfolio","framework","actions","triage","data","reference"];
  const missingFromInfo = realTabs.filter((t) => !tabInfoKeys.includes(t));
  const extraInInfo = tabInfoKeys.filter((t) => !realTabs.includes(t));
  check(missingFromInfo.length === 0, "every real tab has a TAB_INFO entry (no silent tab with an empty hover preview)", JSON.stringify(missingFromInfo));
  check(extraInInfo.length === 0, "TAB_INFO has no stale/typo'd entry for a tab that no longer exists", JSON.stringify(extraInInfo));
} else {
  failures++; console.error("FAIL: could not find the TAB_INFO object in index.html to check against");
}

console.log("--- Anchor-rail links resolve to a real section id (not a typo) ---");
const anchorHrefs = [...indexHtml.matchAll(/class="anchor-rail"[\s\S]*?<\/details>/g)]
  .flatMap((block) => [...block[0].matchAll(/href="#([\w-]+)"/g)].map((m) => m[1]));
check(anchorHrefs.length === 10, "found all 10 expected anchor-rail links (6 on Cost incl. Long-Lead Equipment + Interconnection, 4 on Contingency)", `found ${anchorHrefs.length}`);
const brokenAnchors = anchorHrefs.filter((id) => !indexHtml.includes('id="' + id + '"'));
check(brokenAnchors.length === 0, "every anchor-rail href resolves to a real section id somewhere in the page", JSON.stringify(brokenAnchors));

console.log("--- Tab-drawer click-dismiss fix: structural regression guard ---");
// Found via a real Playwright visual inspection: a mouse click also fires mouseenter on its way
// to the button, arming the drawer's 350ms hover-open timer; the first fix attempt (calling
// hideTabDrawer() in the click handler) didn't clear that pending timer, so the drawer silently
// reopened itself ~350ms after the click -- confirmed live, not assumed. verify.cjs's synchronous,
// no-real-elapsed-time test model can't exercise the actual 350ms timer path directly (accepted
// limitation, stated explicitly rather than skipped silently) -- this is a structural guard that
// the fix's two required pieces are both still present in the source.
check(/function hideTabDrawer\(\)\{ clearTimeout\(tabDrawerTimer\)/.test(indexHtml),
  "hideTabDrawer() clears the pending hover-open timer, not just the 'open' class");
const clickHandlerMatch = indexHtml.match(/btn\.addEventListener\("click", function\(\)\{([\s\S]*?)\n    \}\);/);
check(!!clickHandlerMatch && clickHandlerMatch[1].includes("activateTab(btn.dataset.tab)") && clickHandlerMatch[1].includes("hideTabDrawer()"),
  "the tab button's click handler calls both activateTab() and hideTabDrawer()");

console.log("--- Proactive-framework build (Ada market-challenges doc): structural checks ---");
// Ported per the vault's AdaInfra_MarketChallenges_ProactiveFramework doc: LLE schedule-risk
// (Challenge A), categorized risk buckets (Challenge E), and 2 new live-integrity checks for
// escalation staleness (Challenge B) and cross-region schema drift (Challenge D).
const riskCategoryCount = (indexHtml.match(/category:"(Execution|Escalation|Regulatory & Community)"/g) || []).length;
check(riskCategoryCount === 4, "all 4 risk-register rows carry a category field", `found ${riskCategoryCount}`);
check(indexHtml.includes('var lleItems = ['), "the LLE items array is present");
const lleRealCount = (indexHtml.match(/real:true/g) || []).length;
check(lleRealCount === 2, "exactly 2 LLE rows are badged real (transformer + generator, both independently cited, added 2026-08-26)", `found ${lleRealCount}`);
const guardsBlockMatch = indexHtml.match(/var GUARDS = \[([\s\S]*?)\n  \];/);
check(!!guardsBlockMatch, "found the GUARDS array literal to count structurally");
if (guardsBlockMatch) {
  const guardEntryCount = (guardsBlockMatch[1].match(/\{ n:"/g) || []).length;
  check(guardEntryCount === 13, "GUARDS array literal has exactly 13 check entries", `found ${guardEntryCount}`);
  check(guardsBlockMatch[1].includes("Escalation assumption re-validated"), "the escalation-staleness guard is registered");
  check(guardsBlockMatch[1].includes("Every region reports the same cost-reporting schema"), "the cross-region schema-consistency guard is registered");
}
check(/Substation transformer lead times[\s\S]{0,400}(140|160)/.test(indexHtml), "the LLE section's real-badged citation actually states the 140/160-week transformer figures, not a bare claim");

console.log("--- Director-grade visuals (brainstorm build): structural checks ---");
// 7 new visuals answering the 20-KPI brainstorm's "director-grade" upgrade list: a bullet chart,
// a linear banded gauge, a probability x impact heat-map, an AACE maturity ladder, a CPI
// stoplight grid, and 2 diverging tornado bars -- each reusing an already-computed value, none
// introducing a new fabricated number.
["renderBulletForecast", "renderLinearGauge", "renderRiskHeatmap", "renderMaturityLadder",
 "renderCpiStoplightGrid", "renderCvTornado", "renderSensitivityTornado"].forEach((fn) => {
  check(indexHtml.includes("function " + fn + "("), `${fn}() is defined`);
});
// requestAnimationFrame doesn't exist in verify.cjs's Node vm sandbox -- every one of the 6
// animated visuals must go through the runOnFrame() guard (established pattern: showTabDrawer's
// getBoundingClientRect guard, the Monte Carlo histogram's own requestAnimationFrame guard), never
// call requestAnimationFrame directly, or the headless suite throws before a single assertion runs.
const bareRafCount = (indexHtml.match(/[^.]requestAnimationFrame\(function/g) || []).length;
check(bareRafCount === 0, "no new visual calls requestAnimationFrame() directly -- all go through the guarded runOnFrame() helper", `found ${bareRafCount} bare calls`);
check(indexHtml.includes("function runOnFrame(fn){"), "the shared runOnFrame() guard helper is defined");
// Every new visual's HTML container actually exists, so a render*() call at load time isn't
// silently writing into a null element (document.getElementById would return undefined -> the
// function's own `if (!el) return null` early-return would mask a missing container as "fine").
["bulletForecast", "drawdownGaugeWrap", "riskHeatmap", "maturityLadder", "cpiStoplightGrid",
 "cvTornado", "sensitivityTornado"].forEach((id) => {
  check(indexHtml.includes('id="' + id + '"'), `container #${id} exists in the HTML`);
});
// Every new visual gets its own explainer (the "educational" leg of the interactivity contract) --
// the gauge is the one deliberate exception, sharing the pre-existing exp03 drawdown-ratio formula
// explainer rather than duplicating it for the same underlying number.
["expBullet", "expSensitivity", "expHeatmap", "expStoplight", "expCvTornado", "expMaturity"].forEach((id) => {
  check(indexHtml.includes('data-explainer="' + id + '"'), `${id} explainer button is wired`);
});
// A real bug found via mobile Playwright inspection while verifying the visuals above -- a
// PRE-EXISTING defect, not introduced this build: the 6-column CAPEX Budget Bridge flexbox chart
// has no min-width floor, so its flex:1 columns' text labels force an uncontained ~100px
// horizontal page overflow on a 390px mobile viewport (confirmed via document.documentElement.
// scrollWidth). Fixed the same way 8 tables on this page already handle an oversized child:
// overflow-x:auto wrapper + a min-width floor so bars stay legible instead of being squished to
// illegibility. Committed separately from the director-grade-visuals feature work (B28).
check(/<div style="overflow-x:auto"><div class="bridge" id="bridgeChart"/.test(indexHtml),
  "the CAPEX Budget Bridge chart is wrapped in an overflow-x:auto container (mobile fix)");
check(/\.bridge\{[^}]*min-width:540px/.test(indexHtml),
  "the .bridge chart has a min-width floor so its 6 flex columns can't be squished illegible while scrolling");

console.log("--- Phase 2 director-grade visuals: structural checks ---");
// The remaining 12 visuals from the 20-item brainstorm (the 13th, escalation staleness, was
// already director-grade from the proactive-framework build -- no new work needed there).
["renderNetVarianceTrend", "renderMcScurve", "renderCostDriverTreemap", "renderMarketBenchmarkBar",
 "renderFloatBurndown", "renderEmvTwoBar", "renderConsultantScatter", "renderDqLagTrend",
 "renderLpfDivergingBar", "renderRegionRankedBar", "renderGate4Gauge",
 "renderLineChart", "renderRankedBar"].forEach((fn) => {
  check(indexHtml.includes("function " + fn + "("), `${fn}() is defined`);
});
const bareRafCount2 = (indexHtml.match(/[^.]requestAnimationFrame\(function/g) || []).length;
check(bareRafCount2 === 0, "Phase 2 still has zero direct requestAnimationFrame() calls -- everything routes through runOnFrame()", `found ${bareRafCount2}`);
["netVarianceTrend", "mcScurve", "costDriverTreemap", "marketBenchmarkBar", "floatBurndown",
 "emvTwoBar", "consultantScatter", "dqLagTrend", "lpfRankedBar", "regionRankedBar", "gate4Gauge"].forEach((id) => {
  check(indexHtml.includes('id="' + id + '"'), `container #${id} exists in the HTML`);
});
["expVarianceTrend", "expScurve", "expTreemap", "expFloatBurndown"].forEach((id) => {
  check(indexHtml.includes('data-explainer="' + id + '"'), `${id} explainer button is wired`);
});
// The WBS bar (#10) is a light interactivity upgrade to the EXISTING chart, not a second chart --
// confirm the click-to-detail handler actually landed, not just described in a comment.
check(indexHtml.includes('document.getElementById("wbsDetail")'), "the WBS bar's click-to-detail handler is wired to the real #wbsDetail container");
// Currency-dependent Phase 2 visuals must actually refresh on the currency toggle, the same class
// of gap the proactive-framework build's own riskCategorySubtotals fix closed earlier.
const currencyHandlerMatch = indexHtml.match(/currencySelect\.addEventListener\("change", function\(\)\{([\s\S]*?)\n  \}\);/);
check(!!currencyHandlerMatch, "found the currency-toggle change handler to check against");
if (currencyHandlerMatch) {
  ["renderNetVarianceTrend", "renderCostDriverTreemap", "renderEmvTwoBar", "renderConsultantScatter"].forEach((fn) => {
    check(currencyHandlerMatch[1].includes(fn + "()"), `${fn}() re-renders on currency toggle (it displays a $ figure)`);
  });
}

console.log("--- /stress-test audit (2026-08-26): regression guards for confirmed findings ---");
// Two tornado-bar visuals (built in the first director-grade-visuals commit) were missing
// tabindex="0" -- confirmed by both this session's own review AND an independent fresh-context
// reviewer, the two highest-confidence findings of the whole pass.
check(/id="cvBar' \+ i \+ '" tabindex="0"/.test(indexHtml), "CV tornado bars are keyboard-focusable");
check(/id="sensBar' \+ i \+ '" tabindex="0"/.test(indexHtml), "sensitivity tornado bars are keyboard-focusable");
// 4 dynamic alert/status containers had no aria-live, so slider-driven state changes went
// unannounced to screen readers (independent-reviewer finding).
["drawdownWarn", "floatWarn", "dqWarn", "gateFwStatus"].forEach((id) => {
  check(indexHtml.includes('id="' + id + '" aria-live="polite"'), `#${id} has aria-live="polite"`);
});
// CPI stoplight tiles showed the bare CPI number with no non-color cue, unlike the ledger table's
// own ✓/⚠ right above it on the same tab (independent-reviewer finding).
check(/st-val">' \+ a\.cpi\.toFixed\(2\) \+ ' ' \+ \(ok \? "✓" : "⚠"\)/.test(indexHtml), "CPI stoplight tiles carry a ✓/⚠ marker, not color alone");
// The maturity ladder's "real classification framework" badge had no src-note disambiguating that
// the SPECIFIC class shown (Class 3) is illustrative -- the only new visual missing that pattern.
check(/AACE RP 17R-97 verbatim[\s\S]{0,150}Class 3/.test(indexHtml), "the maturity ladder has its own real-vs-illustrative src-note (Class 3 is illustrative, the 5-class system is real)");
// The "compliance sweep" GUARDS check's own title claimed to scan "this build's own rendered
// content" while only checking 4 hardcoded ids -- broadened to the real set of data-bearing
// containers found by scanning every getElementById(...).innerHTML= call site.
const complianceIdsMatch = indexHtml.match(/var ids = \[("kpiCatalogTable"[\s\S]*?)\];/);
check(!!complianceIdsMatch, "found the compliance sweep's ids array to count");
if (complianceIdsMatch) {
  const complianceIdCount = (complianceIdsMatch[1].match(/"/g) || []).length / 2;
  check(complianceIdCount >= 30, `compliance sweep now scans >=30 real containers, not just 4`, `found ${complianceIdCount}`);
}
// Two branches that no test exercised before this pass: Gate 4's "success" band (the live default
// is always BLOCKED) and the EMV two-bar's "dispute wins" layout (the live default always settles).
check(indexHtml.includes("function computeTwoBarLayout("), "computeTwoBarLayout() was extracted as a pure function specifically so the dispute-wins branch is directly testable");
check(indexHtml.includes("GATE4_GAUGE_BANDS: GATE4_GAUGE_BANDS"), "GATE4_GAUGE_BANDS is exposed to state so its success branch is directly testable");
// The escalation-staleness date math mixed a UTC-parsed date string with a local-time `new Date()`
// "now" -- confirmed via a real probe to cause a rounding-boundary day miscount depending on the
// visitor's timezone, not just a theoretical concern.
check(indexHtml.includes('new Date(lastValidatedStr + "T00:00:00")'), "escalation-age math parses the last-validated date in local time, matching new Date()'s own local-time \"now\"");

console.log("--- ada-fit.html: coverage-brief completeness (JD-gap analysis, 2026-08-26) ---");
// ada-fit.html's own lede claims "requirement-by-requirement coverage" -- a real audit against the
// vault's AdaInfra_JD_InsightMap_2026-08-20.md found it was missing rows for 9 of the JD's 21
// Responsibilities/Requirements lines (6 of 13, 3 of 8). This file has no JS and no verify.cjs
// coverage, so this is a structural row-count floor, not a reconciliation check.
const adaFitHtml = fs.readFileSync(path.join(__dirname, "ada-fit.html"), "utf8");
const adaFitRows = (adaFitHtml.match(/<tr><td class="req">/g) || []).length;
check(adaFitRows === 22, "ada-fit.html has all 22 coverage rows (13 Responsibilities + 9 Requirements, matching every JD line in the InsightMap doc)", `found ${adaFitRows}`);

console.log("--- Glossary: every category has a real render target, not just a filter/count entry ---");
// Real bug found and fixed in this same pass: adding a 4th "vocab" glossaryCategories entry without
// a matching <dl> container + renderCategory() call left it correctly counted/filterable but
// invisibly unrendered -- the category button existed, its items never appeared. Generalized so
// ANY future category addition trips this the moment it's added, not after another live bug.
const catKeysMatch = indexHtml.match(/var glossaryCategories = \[([\s\S]*?)\];/);
check(!!catKeysMatch, "found the glossaryCategories array to check against");
if (catKeysMatch) {
  const catKeys = [...catKeysMatch[1].matchAll(/key:"(\w+)"/g)].map((m) => m[1]).filter((k) => k !== "all");
  // The real invariant: a renderCategory(containerId, categoryKey) call whose SECOND argument is
  // this key -- not an assumption about how the container id is spelled (a pre-existing category
  // is "figures" rendering into id="figureGlossary", singular; naming isn't 1:1 and that's fine).
  const renderCalls = [...indexHtml.matchAll(/renderCategory\("(\w+)",\s*"(\w+)"\)/g)];
  const renderedKeys = renderCalls.map((m) => m[2]);
  const containerIds = renderCalls.map((m) => m[1]);
  const missingRenderCall = catKeys.filter((k) => !renderedKeys.includes(k));
  check(missingRenderCall.length === 0, "every non-'all' glossary category has a matching renderCategory() call", JSON.stringify(missingRenderCall));
  const missingContainer = containerIds.filter((id) => !indexHtml.includes(`id="${id}"`));
  check(missingContainer.length === 0, "every renderCategory() target id has a matching <dl> container in the HTML", JSON.stringify(missingContainer));
}

console.log("--- Interconnection Cost & Schedule Exposure (20-item deep-research pass, 2026-08-26) ---");
check(indexHtml.includes("function computeInterconnectionExposure("), "computeInterconnectionExposure() is defined");
check(indexHtml.includes('id="interconnection-section"'), "the interconnection section exists in the HTML");
check(indexHtml.includes('id="interconnectionDollar"') && indexHtml.includes('id="interconnectionWarn"'), "both interconnection render targets exist in the HTML");
check(indexHtml.includes('data-explainer="expInterconnection"'), "expInterconnection explainer button is wired");
check(currencyHandlerMatch && currencyHandlerMatch[1].includes("renderInterconnectionExposure()"), "renderInterconnectionExposure() re-renders on currency toggle (it displays a $ figure)");
check(indexHtml.includes('interconnectionResult: interconnectionResult'), "interconnectionResult is exposed to state for direct testing");
// LLE citation upgrade: the generator row is now a second independently-cited real figure, not
// just the transformer -- confirm the source text actually states the new range, not a bare claim.
check(/50–78 weeks[\s\S]{0,200}90–110 weeks/.test(indexHtml), "the LLE section's src-note states the real generator lead-time range (50-78wk / 90-110wk), not a bare claim");
// Independent-reviewer finding: the generator claim shared the transformer claim's citation names
// by proximity (the section-scoped "explained somewhere" check would have passed either way) but
// carried no citation of its own. Confirm the generator figure now names its own distinct sources
// (Terrapin, PowerMag), not just relying on Wood Mackenzie/Turner & Townsend appearing earlier for
// the transformer claim in the same paragraph.
check(/Terrapin Consulting Group's own 2026 lead-time survey/.test(indexHtml), "the generator lead-time figure has its own named source (Terrapin), distinct from the transformer citation");
check(/PowerMag's 2026\s+reporting confirms/.test(indexHtml), "the Cummins sold-out-through-2028 claim has its own named source (PowerMag)");

console.log("--- ada-fit.html: self-referential rows hedge consistently (independent-reviewer finding) ---");
// The "Develop cost-focused KPI views" row cited the dashboard itself as supporting evidence for a
// "Match" without the same "illustrates the claim, isn't the proof" hedge every other
// self-referential row in this file uses -- a real tonal inconsistency, now fixed.
check(/they illustrate the claim, they aren't themselves the proof of prior experience/.test(adaFitHtml), "the KPI-views row's dashboard reference is hedged the same way as every other self-referential row in the file");

console.log("");
if (failures > 0) {
  console.error(failures + " stress check(s) FAILED");
  process.exit(1);
} else {
  console.log("All stress checks passed.");
  process.exit(0);
}
